### ISSUE TITLE
Stories getting in twice, sometimes ... 

### ISSUE THREAD

**Issue by jheasly** [registerguard/ap_wfm#24]
```python
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 47, in view
    return self.dispatch(request, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in dispatch
    return handler(request, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/django/views/generic/detail.py", line 98, in get
    self.object = self.get_object()

  File "/usr/lib/python2.7/dist-packages/django/views/generic/detail.py", line 49, in get_object
    obj = queryset.get()

  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    % (self.model._meta.object_name, num, kwargs))

MultipleObjectsReturned: get() returned more than one APStory -- it returned 2! Lookup parameters were {}
```

**Comment by jheasly** [comment]
I think we've a race condition and I'm going to fix it.

**Comment by jheasly** [comment]
Got each APExchange search writing to its own log file, which is progress. Previously, every search was writing to one log file, so it was a confusing, useless mishmash.  
Now we have:
![screenshot 2015-03-25 15 40 49](https://cloud.githubusercontent.com/assets/96007/6837072/636b6d5a-d305-11e4-9573-efde7de34733.png)
Much better! (And more useful.)  
Next, `updating` rather than `deleting` previous versions of `APStories` in `process_feed.py`. Hopefully db locks will do behave in a useful way. We shall see (now that we have useful logs!).

**Comment by jheasly** [comment]
Now that we're [UPDATING, not DELETING](https://github.com/registerguard/ap_wfm/commit/7330ded9b3d31900b5fb5e7c409d943d66fd41f9), the update otta check and see if there're two stories found and at least log this, if not nuke one.

```bash
2015-03-27 16:31:30,782: ap_wfm.management.commands.process_feed - DEBUG - >>> Script called.
2015-03-27 16:31:30,783: ap_wfm.management.commands.process_feed - DEBUG - /rgcalendar/oper/projects_root/ap_wfm/WFA/feeds/Washington-State-JH/feed_650990_2015-03-27T23-31-30.125Z.xml passed to script.
2015-03-27 16:31:30,783: ap_wfm.management.commands.process_feed - DEBUG - >>> STARTING /Washington-State-JH/feed_650990_2015-03-27T23-31-30.125Z.xml
2015-03-27 16:31:30,786: ap_wfm.management.commands.process_feed - DEBUG - >>> Feeding 'wash' section.
2015-03-27 16:32:15,836: ap_wfm.management.commands.process_feed - DEBUG - >>> Skip Title fragments: ('HKO-WHL', 'LOT--', 'USDA-Portland', 'Box, BKC')
2015-03-27 16:32:15,836: ap_wfm.management.commands.process_feed - DEBUG -     US-Gay-Wedding-Florist
2015-03-27 16:32:15,849: ap_wfm.management.commands.process_feed - DEBUG - XXX Older version look-up based on slug: 'us-gay-wedding-florist', management_id: c8725bf9e7f349e8994f7cda6c643c79 XXX
2015-03-27 16:32:15,987: ap_wfm.management.commands.process_feed - DEBUG - XXX Found older version: [<APStory: Washington florist hit with $1,001 fine for refusing to sell flowers for a same-sex wedding ID:3762019>, <APStory: Washington florist who refused to sell flowers for gay wedding rejects settlement on bias case ID:3741438>] XXX
2015-03-27 16:32:16,007: ap_wfm.management.commands.process_feed - DEBUG - XXX UPDATED US-Gay-Wedding-Florist XXX
2015-03-27 16:32:16,013: ap_wfm.management.commands.process_feed - DEBUG - XXX UPDATED US-Gay-Wedding-Florist XXX
2015-03-27 16:32:16,015: ap_wfm.management.commands.process_feed - DEBUG -       0 images with this story.
```
