### ISSUE TITLE
Internal Server Error: /apf/feeds/rss/

### ISSUE THREAD

**Issue by jheasly** [registerguard/ap_wfm#26]
Look into this. I didn't even know I'd made/remember making an RSS feed URL(!).
It's mostly (all?) requests from `+https://code.google.com/p/feedparser/`

```python
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.38.0.31/newrelic/hooks/framework_django.py", line 497, in wrapper
    return wrapped(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/django/contrib/syndication/views.py", line 37, in __call__
    feedgen = self.get_feed(obj, request)

  File "/usr/lib/python2.7/dist-packages/django/contrib/syndication/views.py", line 148, in get_feed
    self.__get_dynamic_attr('item_link', item),

  File "/usr/lib/python2.7/dist-packages/django/contrib/syndication/views.py", line 70, in __get_dynamic_attr
    return attr(obj)

  File "/usr/lib/python2.7/dist-packages/django/contrib/syndication/views.py", line 51, in item_link
    return item.get_absolute_url()

  File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 55, in _curried
    return _curried_func(*(args+moreargs), **dict(kwargs, **morekwargs))

  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 887, in get_absolute_url
    return settings.ABSOLUTE_URL_OVERRIDES.get('%s.%s' % (opts.app_label, opts.module_name), func)(self, *args, **kwargs)

  File "/rgcalendar/oper/projects_root/ap_wfm/models.py", line 91, in get_absolute_url
    return '/apf/%s/%s/' % (self.category.all()[0].get_name_display(), self.slug)

  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 206, in __getitem__
    return list(qs)[0]

IndexError: list index out of range
```

**Comment by jheasly** [comment]
Problem is caused by APStories getting inserted without a `category`. See #28.
